#!/usr/bin/python3
import os
import subprocess as sub


def runcmd(cmd):
    if "date" in cmd:
        output=sub.getoutput(cmd)
        print("\t{0}".format(output))
    elif "cal" in cmd:
        output=sub.getoutput(cmd)
        output="    "+output.replace('\n','\n\t')
        print(output)
    else:
        out=sub.getoutput(cmd)
        print(out,"\n")

def help():
    print("\t\tMAIN MENU")
    print()
    print("\tdate-> to show date & time")
    print("\tcal->to show calender")
    print("\treboot-> to reboot the system")
    print("\tshutdown-> to shutdown the system")
    print("\tram_s-> to show status of RAM")
    print("\tcpu_s-> to show status of cpu")
    print("\tdisk_s-> to show available disk status")
    print("\tip-> to show ip address of system")
    print("\tPress 1 to configure httpd server")
    print("\tPress 2 to remote login via ssh")
    print("\tPress 3 to configure Hadoop DFS")
    print("\tPress 4 to to upload files using scp protocol")
    print("\tPress 5 to show running docker image status")
    print("\tPress 6 to show available os images")
    print("\tPress 7 to install docker image:")
    print("\tPress 8 to show data of packets(payload) passes over network/Internet:")
    print()

def helphttpd():
    print("\t\thttpd SERVER MENU")
    print()
    print("\tEnter 1 to start httpd server")
    print("\tEnter 2 to stop httpd server")
    print("\tEnter 3 to start firewall of system")
    print("\tEnter 4 to stop firewall of system")
    print("\tEnter 5 to show status of httpd server")
    print()

def helphadoop():
    print("\t\tApache Hadoop MENU")
    print()
    print("\tEnter 1 to Start Masternode.")
    print("\tEnter 2 to start Datanode.")
    print("\tEnter 3 to show dfs cluster report.")
    
    print()
    
   
    
os.system("tput setaf 3")
print("\twelcome to mycmd menu ")
print("\t\tmy command line...\n")
print("\tEnter h for help ")
print("\tEnter q to quit")
os.system("tput setaf 2")
while True:
    os.system("tput setaf 2")
    cmd=input("\tEnter your command>>")
    if "q" in cmd:
        os.system("tput setaf 7")
        break
    elif "h" in cmd:
        help()
      
    elif "date" in cmd:
        runcmd("date")
    elif "cal" in cmd:
        runcmd("cal")
    elif "reboot" in cmd:
        os.system("init 6")

    elif "shutdown" in cmd:
        os.system("init 0")

    elif "ram_s" in cmd:
        runcmd("free -m")

    elif "cpu_s" in cmd:
        runcmd("lscpu")
    
    elif "disk_s" in cmd:
        runcmd("fdisk -l")
    elif "ip" in cmd:
        os.system("ifconfig")
    elif "1" in cmd:
        print("\t\thttpd command line...")
        print("\tEnter h for help")
        while True:
            print()
            cmd=input("\tEnter your choice:")
            print()
            if "q" in cmd:
                print("\t\tmy command line...")
                print()
                break
            elif "h" in cmd:
                helphttpd()
            elif "1" in cmd:
                out=os.system("systemctl start httpd")
                if out==0:
                    print("\tSuccessfully started httpd server.")
                    print()
                else:
                    print("\tError something goes wrong!")
                    print()

            elif "2" in cmd:
                out=os.system("systemctl stop httpd")
                if out==0:
                    print("\tSuccessfully stopped httpd server.")
                    print()
                else:
                    print("\tError something goes wrong!")
                    print()
            elif "3" in cmd:
                out=os.system("systemctl start firewalld")
                if out==0:
                    print("\tSuccessfully started firewall.")
                    print()
                else:
                    print("\tError something goes wrong!")
                    print()
            elif "4" in cmd:
                out=os.system("systemctl stop firewalld")
                if out==0:
                    print("\tSuccessfully stopped firewall.")
                    print()
                else:
                    print("\tError something goes wrong!")
                    print()
            elif "5" in cmd:
                out=sub.getstatusoutput("systemctl status httpd")
                if out[0]==0:
                    print("\tRunning...")
                    print()
                else:
                    print("\tStopped...")
                    print() 
	
    elif "2" in cmd:
        ip=input("Enter ip:")
        os.system("ssh {}".format(ip))

    elif "3" in cmd:
        print("\t\tHadoop command line...")
        print("\tEnter h for help")
        while True:
            print()
            cmd=input("\tEnter your choice:")
            print()
            if "h" in cmd:
                helphadoop()
            elif "q" in cmd:
                print("\t\tmy command line...")
                print()
                break
            elif "1" in cmd:
                pass
            elif "2" in cmd:
                pass
            elif "3" in cmd:
                pass
    elif "4" in cmd:
        file=input("Enter file name to be uploaded:")
        path=input("Enter path (ip address):/path ")
        os.system("scp {0} {1}".format(file,path))
    elif "5" in cmd:
        runcmd("docker ps")
    elif "6" in cmd:
        runcmd("docker images")
    elif "7" in cmd:
        print("\tAvailable Docker Images\n")
        out=sub.getoutput("docker images")
        print(out,"\n")
        img=input("\tEnter docker image name:")
        os.system("docker run -i -t {}".format(img)) 
        
        
    else:
        os.system("tput setaf 1")
        print("\tinvalid command")
        os.system("tput setaf 2")

